### ISSUE TITLE
2.2.0 Compatibility

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#10]
Hey guys,

thanks for your latest help within my feature request. This time I just want to know if there's a timeline for a 2.2 compatible version?

Greetings
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
this is indeed a valid question. Magento 2.2 has just recently become stable enough so we can do serious development for it. Our development process now takes Magento 2.2 into account.

However, I can't give you an exact date when the module will be officially compatible with Magento 2.2, since it hasn't event been released yet. Sorry I can't be more precise here.

**Comment by gewaechshaus** [comment]
@ngolatka - thanks a lot!

**Comment by Merik95** [comment]
Hello,
how is the state with the Magento 2.2 compability? 
We would like to update from 2.1.13 to 2.2 But need this DHL module.

**Comment by mam08ixo** [comment]
DHL Shipping runs on 2.2 – any issues with that?
