### ISSUE TITLE
Missing source class

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#11]
Hey netresearchers,

under MCE2.2.0 and php7.1 there's is the following error coming up while running setup:di:compile. 
Installed the 0.6.0 archive in app/code... (I know 2.2.0/7.1 aren't officially supported)

    [RuntimeException]
    Source class "\Dhl\Shipping\Webservice\AppData" for "Dhl\Shipping\Webservice\AppDataMapper" generation does not exist.

Grüße
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
That is a bit strange. We didn't encounter this problem during our tests. The PHP version shouldn't be the cause for this problem.

A few questions:
- Did you install the module via "drop in" as explained in the readme? Then please try again installing it via Composer / VCS. Maybe the [library for the module](https://github.com/netresearch/dhl-lib-shipping-mx) wasn't installed properly.
- Our Magento instance was in [development-mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html). Do you get this error in production-mode only? If yes, can you change the mode and try again?
- Do you have any other hints on how we could reproduce this problem?

**Comment by gewaechshaus** [comment]
Hey @ngolatka,

- Yes, as drop in
- Can't install by composer cause of the missing ~7.1.0 string in the dhl/module-shipping-m2 requirements -> PR https://github.com/netresearch/dhl-module-shipping-m2/pull/12
- Running in production mode
- I will view the logs now

**Comment by mam08ixo** [comment]
@gewaechshaus The [drop-in is a ZIP archive](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.6.0/README.md#drop-in) that contains the merged sources of two different repositories. You did not receive such a ZIP file, so you cannot install into `app/code/`. To install from VCS on a machine running PHP7.1, simply add the `--ignore-platform-reqs` composer option during installation.

**Comment by gewaechshaus** [comment]
@mam08ixo - ok. Thanks for clarifying this, I just downloaded the zipped release https://github.com/netresearch/dhl-module-shipping-m2/releases .  I will go on to install it by composer...

**Comment by gewaechshaus** [comment]
Composer install did work, di compilation also. Will go on with some functional testing. This issue can be closed...

**Comment by ngolatka** [comment]
@gewaechshaus 
Thanks for letting us know!

General FYI for anyone who runs into the same problem:
Github automatically provides a ZIP and TGZ of the repository. However, this is not the ZIP that is intended for a drop-in installation (as mentioned in the [readme](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/README.md)), because it does not contain the merged sources (main module **and** library).

End result: the preferred way for installation is Composer, which will take care of the dependencies. The [readme](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/README.md) tells you what needs to be done.
