### ISSUE TITLE
add all products by default

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#32]
**Feature description**
When I create a shipment for a new order,
I want to have all products of that order already added by default.
The user still has the ability to remove items or change their count as it is now.

**Reason**

1. Loading all products,
2. then selecting them all,
3. then adding all selected products
needs to be performed manually for every single order.
In 99% of all cases no change to the list of items needs to be performed.
Thus wasting a lot of time and effort.

**Additional context**
n/a

**Comment by ngolatka** [comment]
@MarcusWolschon I understand your problem, but that workflow is not meant to be used for high order volumes. For that, there are the various mass-actions (via Cronjob, or by selecting orders in the list). Those will drastically reduce the amount of work.

The popup was taken from Magento Core, hence the somewhat cumbersome usage. We are however not planning to modify that, because we want to stick to the Mage Core behaviour as close as possible.
