### ISSUE TITLE
Bug in admin: Exception "Undefined index" when unsupported origin country is set

### ISSUE THREAD

**Issue by fredrikblanco** [netresearch/dhl-module-shipping-m2#37]
After installing the latest version, (0.9.1) we cannot access the shipping methods settings, the system returns: 
"Exception #0 (Exception): Notice: Undefined index: BR in /home/magento2/grand-combin/vendor/dhl/lib-shipping-mx/Util/ShippingProducts.php on line 506
"
After removing the module, it works again.

**Comment by mam08ixo** [comment]
Hi @fredrikblanco 

thank you for reporting this issue. The error occurs when a shipping origin is configured which is not supported by the module.

Until the bug is fixed in an upcoming version, I suggest setting the shipping origin to a country that can be shipped from using _DHL Shipping_ (which is necessary anyway to use the module).

`Stores → Configuration → Sales → Shipping Settings → Origin → Country`

For a list of supported origin-destination routes, please refer to [`ShippingRoutes::getRoutes()`](https://github.com/netresearch/dhl-lib-shipping-mx/blob/0.9.0/Util/ShippingRoutes.php#L48-L107).

**Comment by sfblaauw** [comment]
Any news? also ES. Thanks

**Comment by ngolatka** [comment]
@sfblaauw
This issue is going to be fixed in version 0.10.0, which we plan to release shortly (as mentioned in issue #44).

**Comment by ngolatka** [comment]
The new [version 0.10.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.0) is available which resolves this issue.

**Comment by fredrikblanco** [comment]
Great, thanks for the info

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
