### ISSUE TITLE
Return Label

### ISSUE THREAD

**Issue by leanderf** [netresearch/dhl-module-shipping-m2#41]
Hi there,

I just wanted to ask whether the Magento built-in retrun management can be used with the M2 DHL extension. I found some code responsible for return management, but no section about that in the documentation. Is it already possible to generate shipping labels as a valid customer?
Or will this be an upcoming feature?

Thank you !

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [X] Yes, but couldn't find anything
http://dhl.support.netresearch.de/support/solutions/articles/12000026789-where-can-i-get-the-latest-version-of-the-online-returns-module-

**Comment by ngolatka** [comment]
Hello @leanderf 
the DHL module does not interact with the Return Management in Magento 2 EE. What the module offers is to create a DHL return label which can be printed, put into the package, and sent to the customer. The customer can then use it for return shipments, if necessary.

This is included in the module since version 0.6.0 and mentioned in the [documentation](https://marketplace.magento.com/media/catalog/product/dhl-module-shipping-m2-0-9-0-ce/user_guides.pdf) on pages 8, 13, and 16.
