### ISSUE TITLE
Timelines not kept for over one year now

### ISSUE THREAD

**Issue by andidhouse** [netresearch/dhl-module-shipping-m2#5]
This is not a technical bug reported, but more important a timeline bug.

The extension was promised in a full working version End 2016 on the website. Then it was beginning of 2017 - then end of Q6 as you can see here:

https://www.netresearch.de/blog/neue-dhl-magento-extensions-versenden-und-dhl-standortsuche/

It is now again over the timeline. Could you pls tell us why it is not possible to build a fully working extension (not alpha or beta). The development now goes on for far over 1 year! and it is still only a beta version available (which is in not case suitable for a production system).

We have found now 3 other solutions for our biggest shops - we are still waiting for this for one of you small shops but really loose trust in a) the company that develops the extension and promotes the timelines which are not hold at all and b) DHL why they do not react here. 

Thanks for a feedback if this extension will ever be published next time (and i do not mean 2018 or 2019 with next time...

**Comment by powli** [comment]
You're right, the scheduled timeline could not be met. And we are not satisfied either.

But as everything in real life, this has multiple reasons. Necessary fixes in the early life cycle on the part of Magento core were just one of them, as well as some delays and necessary modifications around the new DHL Shipping API and also jointly agreed changes in concept, functional scope and priority, like the integration of additional DHL shipping webservices into the extension. 

Due to this the extension will no longer only support shipments from DE/AT to EU, but also allow cross border shipping and international shipping origins. We are developing on behalf of the DHL and are in permanent close contact here and prioritize the features together.

We are currently targeting a new release with cross border and basic addon service functionality in September/Oktober 2017.

**Comment by andidhouse** [comment]
@powli thanks for pointing that out. At last we know now that we will not use the module. A timeline over 1 year late - we can not handle that in planning for our shops.

I also wonder why other carrier (for example DHL America) can manage to get this working from the beginning on?

Thanks again for pointing this out so we know where this stands.
