### ISSUE TITLE
Customize Store Name used in Sender Address

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#57]
**Feature description**
The sender address used does include the store name, followed by company name and address as a "from" address.
It should be possible to ommit or customize the store name used here.

**Reason**
There are stores with higher privacy expectations where neighbours and delivery personal should not see from the label that a customer ordered from a specific website.

**Comment by powli** [comment]
Hello @MarcusWolschon,

the shipper information used in the request is constructed [here](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/Webservice/AppDataMapper.php#L340-L368). Nearly all the data is provided by the `ShipmentRequest` model that gets passed in from the Magento Core into our Carrier [here](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/Model/Shipping/Carrier.php#L275).
The relevant core model with a public API is [AbstractCarrierOnline](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Shipping/Model/Carrier/AbstractCarrierOnline.php#L486).

Since the need to hide/obfuscate/swap the store name is a merchant specific business requirement, I'd rather opt for a custom solution on your part.
The problem can most likely be solved with a simple beforePlugin on the `AbstractCarrierOnline::requestToShipment` method, altering the information that gets passed down in the `ShipmentRequest`.

**Comment by MarcusWolschon** [comment]
Thanks a lot!
