### ISSUE TITLE
can't use DHL Shipping when the Origin is Saudi Arabia

### ISSUE THREAD

**Issue by growsera** [netresearch/dhl-module-shipping-m2#61]
Hi All,
i tried to use DHL Shipping but it doesn't work when i choose Saudi Arabia as origin !

kindly help

**Comment by ngolatka** [comment]
Hello @MagentoAr 
that's not a bug in the module. The DHL Shipping module cannot be used for your country, because the DHL APIs which the module uses do not support it.

Please see the [documentation](https://dhl-sharing.nrdev.de/modules/versenden-shipping/mage2/.public/DHL_Shipping_UserGuide_EN.pdf), page 5 for a list of supported countries.

Sorry, but I'm afraid you can't use the DHL Shipping module for your scenario.
