### ISSUE TITLE
Compatibility with wirecard/magento2-ee

### ISSUE THREAD

**Issue by bheindl** [netresearch/dhl-module-shipping-m2#70]
**Feature description**
Right now this module is not compatible with payment module from wirecard (wirecard/magento2-ee).

**Reason**
DHL modules (as one of the shipping marketleaders) should be compaticle with Wirecard payment modules (as one of the payment marketleaders).

**Additional context**
Composer installation fails, because DHL modules require php-http packages in old ^1.0 versions, but wirecard already uses new php-http packages in ^2.0 versions. As wirecard uses the current versions of the php-http packages, DHL modules should be migrated to use them as well.

**Comment by mam08ixo** [comment]
I executed the following:

```
$ composer require dhl/module-shipping-m2:0.11.0
$ composer require wirecard/magento2-ee:^v3.0.0

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/discovery (locked at 1.7.4) -> satisfiable by php-http/discovery[1.7.4].
    - wirecard/magento2-ee v3.0.0 requires php-http/discovery 1.4.0 -> satisfiable by php-http/discovery[1.4.0].
    - wirecard/magento2-ee v3.0.1 requires php-http/discovery 1.4.0 -> satisfiable by php-http/discovery[1.4.0].
    - Conclusion: don't install php-http/discovery 1.4.0
    - Installation request for wirecard/magento2-ee ^v3.0.0 -> satisfiable by wirecard/magento2-ee[v3.0.0, v3.0.1].
```

I can confirm the two modules are currently not compatible because Wirecard requires a fixed, old version of the `php-http/discovery` package. I do not know why they do not allow more recent versions of the package.

As a workaround you could install `dhl/module-shipping-m2:0.10.3` (with `--ignore-platform-reqs` if necessary). The module version 0.10.3 does not require any HTTPlug or psr / php-http packages.

**Comment by ngolatka** [comment]
Closed because `dhl-module-shipping-m2` is not maintained anymore.
