### ISSUE TITLE
User name as contact

### ISSUE THREAD

**Issue by Merik95** [netresearch/dhl-module-shipping-m2#8]
On the shipping label the name of the Magento user, who create the shipping label is also printed. I believe most shops do not want the user name to be printed on the label, but only the shop name and adress.

**Comment by ngolatka** [comment]
Hello @Merik95
we have in fact made some changes here which are not yet visible on Github. The name will not be shown in the "From" field anymore, but instead in the smaller "Contact info" field at the top right.

However, we have intentionally not removed the name completely, because in our experience, the merchants want to offer some point of contact.

If you don't want a real name to be shown here, you could edit the name of the Admin User in Magento which is used to create the shipment (maybe to something a bit more anonymous).

**Comment by MerikMag** [comment]
Hello ngolatka,
thank you very much for the fast answer.
We have different users, which are creating the shipment label, but we do not want them to be shown to customer. On the other hand we want to have different user names for logging of activities.
So changing the user name is not an option.
In which file the shipping label is created? We then will simple comment out the line with the user name.

**Comment by ngolatka** [comment]
@MerikMag This does not happen inside the [dhl-module-shipping-m2 module](https://github.com/netresearch/dhl-module-shipping-m2), but in the [library](https://github.com/netresearch/dhl-lib-shipping-mx) instead.

The relevant part is in

_dhl-lib-shipping-mx/Webservice/RequestType/CreateShipment/ShipmentOrder/Contact/Shipper.php_

in the function _getContactPerson_

**HOWEVER**, keep in mind: if you modify the module, we might not be able to provide technical support in the future. Also, there's no guarantee that modifications will still work in future versions.

**Comment by MarcusWolschon** [comment]
The local user names of whatever account was logged into the admin UI for creating the postage
is absolutely nothing the customer should ever see.
("admin", "android management app", ...)
It is also completely useless as contact info.
The shop defines a global contact email address.
That and only that is the contact a user must ever use and see to reach the CRM system.
Users trying out any random (technical user)@shop.tld because they try to be clever
mean their communication is either lost (technical account)/never reat(user on vacation)/reaches users not tasked with or authorized for customer communication and thus leading to poor customer support.
At the very least it means the communication never shows up in the CRM as context if the user uses the correct communication address later and refers to earlier emails.

**Comment by ngolatka** [comment]
Dear @MarcusWolschon 
there are some things that I'd like to clarify:
- Neither the username nor the email address of an admin user are printed on the shipping label. What you see is firstname + lastname + phone number, not the login (like "admin").
- The shipper communication details (contact person, phone) help the carrier to resolve issues during delivery. From a carrier perspective, that makes total sense.
- If you still want to change that behavior, you are perfectly free to maintain your own fork of this open source software.
- However, keep in mind that [our technical support](http://dhl.support.netresearch.de/support/tickets/new) is limited to the vanilla version we provide. We cannot and will not provide in-depth support for modified versions of our software.

**Comment by MarcusWolschon** [comment]
Does the API allow for an empty "companyName"  and empty "phone" in the Shipper?
Is NULL an allowed value? (The inline documentation is rather lacking in this regard.)

**Comment by ngolatka** [comment]
According to DHL's IO Reference which is available in the [DHL Developer Portal](https://entwickler.dhl.de/en/web/ep/welcome), the shipper company name (name2) and shipper phone number are optional.
